In [3]:
import pandas as pd

In [4]:
import numpy as np

In [8]:
df = pd.read_csv('student_portuguese_clean.csv')

In [9]:
df

,student_id,school,sex,age,address_type,family_size,parent_status,mother_education,father_education,mother_job,...,family_relationship,free_time,social,weekday_alcohol,weekend_alcohol,health,absences,grade_1,grade_2,final_grade
0,1,GP,F,18,Urban,Greater than 3,Apart,higher education,higher education,at_home,...,4,3,4,1,1,3,4,0,11,11
1,2,GP,F,17,Urban,Greater than 3,Living together,primary education (4th grade),primary education (4th grade),at_home,...,5,3,3,1,1,3,2,9,11,11
2,3,GP,F,15,Urban,Less than or equal to 3,Living together,primary education (4th grade),primary education (4th grade),at_home,...,4,3,2,2,3,3,6,12,13,12
3,4,GP,F,15,Urban,Greater than 3,Living together,higher education,5th to 9th grade,health,...,3,2,2,1,1,5,0,14,14,14
4,5,GP,F,16,Urban,Greater than 3,Living together,secondary education,secondary education,other,...,4,3,2,1,2,5,0,11,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,645,MS,F,19,Rural,Greater than 3,Living together,5th to 9th grade,secondary education,services,...,5,4,2,1,2,5,4,10,11,10
645,646,MS,F,18,Urban,Less than or equal to 3,Living together,secondary education,primary education (4th grade),teacher,...,4,3,4,1,1,1,4,15,15,16
646,647,MS,F,18,Urban,Greater than 3,Living together,primary education (4th grade),primary education (4th grade),other,...,1,1,1,1,1,5,6,11,12,9
647,648,MS,M,17,Urban,Less than or equal to 3,Living together,secondary education,primary education (4th grade),services,...,2,4,5,3,4,2,6,10,10,10
648,649,MS,M,18,Rural,Less than or equal to 3,Living together,secondary education,5th to 9th grade,services,...,4,4,1,3,4,5,4,10,11,11

In [17]:
df['sex']

0      F
1      F
2      F
3      F
4      F
      ..
644    F
645    F
646    F
647    M
648    M
Name: sex, Length: 649, dtype: object

In [18]:
df['sex'] = df['sex'].map({"F":0,"M":1})

In [19]:
df['sex']

0      0
1      0
2      0
3      0
4      0
      ..
644    0
645    0
646    0
647    1
648    1
Name: sex, Length: 649, dtype: int64

In [20]:
df.rename(columns={df.columns[2]: "isFemale"}, inplace=True)

In [21]:
df['parent_status'].value_counts()

parent_status
Living together    569
Apart               80
Name: count, dtype: int64

In [26]:
columns = ["school","isFemale","age","family_size"]

In [27]:
# columns = ["school","sex","age","family_size"]
df[columns]

    school  isFemale  age              family_size
0       GP         0   18           Greater than 3
1       GP         0   17           Greater than 3
2       GP         0   15  Less than or equal to 3
3       GP         0   15           Greater than 3
4       GP         0   16           Greater than 3
..     ...       ...  ...                      ...
644     MS         0   19           Greater than 3
645     MS         0   18  Less than or equal to 3
646     MS         0   18           Greater than 3
647     MS         1   17  Less than or equal to 3
648     MS         1   18  Less than or equal to 3

[649 rows x 4 columns]

In [29]:
df['family_size'].value_counts()

family_size
Greater than 3             457
Less than or equal to 3    192
Name: count, dtype: int64