In [37]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression

### TEST 1

In [38]:
df = pd.read_csv('dataset/real_dataset_100.csv')

In [39]:
df

    Sepal_Length  Sepal_Width  Petal_Length Weather_Condition  Target_Output
0            6.1          2.8           4.7            Cloudy              0
1            5.7          3.8           1.7            Cloudy              0
2            7.7          2.6           6.9             Rainy              1
3            6.0          2.9           4.5             Rainy              0
4            6.8          2.8           4.8            Cloudy              0
..           ...          ...           ...               ...            ...
95           5.5          2.5           4.0             Sunny              0
96           4.4          2.9           1.4             Rainy              0
97           4.3          3.0           1.1             Rainy              0
98           6.0          2.2           5.0            Cloudy              1
99           7.2          3.2           6.0             Sunny              1

[100 rows x 5 columns]

In [40]:
y = df['Target_Output']

In [41]:
del(df['Target_Output'])

In [42]:
X = df

In [43]:
del(df['Weather_Condition'])

In [44]:
X

    Sepal_Length  Sepal_Width  Petal_Length
0            6.1          2.8           4.7
1            5.7          3.8           1.7
2            7.7          2.6           6.9
3            6.0          2.9           4.5
4            6.8          2.8           4.8
..           ...          ...           ...
95           5.5          2.5           4.0
96           4.4          2.9           1.4
97           4.3          3.0           1.1
98           6.0          2.2           5.0
99           7.2          3.2           6.0

[100 rows x 3 columns]

In [45]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [46]:
print('Intercept:', model.intercept_)
print('Coefficient:', model.coef_)

Intercept: -0.8971871129511384
Coefficient: [-0.04955999  0.21116098  0.23257966]

### TEST 2

In [47]:
df1 = pd.read_csv('dataset/real_dataset_100.csv')

In [48]:
y1 = df1['Target_Output']

In [49]:
del(df1['Target_Output'])

In [50]:
X1 = df1

In [51]:
df1['Weather_Condition']=100

In [52]:
X1

    Sepal_Length  Sepal_Width  Petal_Length  Weather_Condition
0            6.1          2.8           4.7                100
1            5.7          3.8           1.7                100
2            7.7          2.6           6.9                100
3            6.0          2.9           4.5                100
4            6.8          2.8           4.8                100
..           ...          ...           ...                ...
95           5.5          2.5           4.0                100
96           4.4          2.9           1.4                100
97           4.3          3.0           1.1                100
98           6.0          2.2           5.0                100
99           7.2          3.2           6.0                100

[100 rows x 4 columns]

In [53]:
model = LinearRegression()
model.fit(X1, y1)

LinearRegression()

In [54]:
print('Intercept:', model.intercept_)  ##0.8915528991007522
print('Coefficient:', model.coef_)

Intercept: -0.8971871129511388
Coefficient: [-0.04955999  0.21116098  0.23257966  0.        ]

### TEST 3

In [91]:
df2 = pd.read_csv('dataset/real_dataset_100.csv')

In [92]:
encoding = df2['Weather_Condition']

In [93]:
encoding = pd.get_dummies(df2['Weather_Condition'],prefix="Is").astype(int)

In [94]:
encoding

    Is_Cloudy  Is_Rainy  Is_Sunny
0           1         0         0
1           1         0         0
2           0         1         0
3           0         1         0
4           1         0         0
..        ...       ...       ...
95          0         0         1
96          0         1         0
97          0         1         0
98          1         0         0
99          0         0         1

[100 rows x 3 columns]

In [95]:
df2=pd.concat([df2,encoding],axis=1)

In [96]:
df2

,Sepal_Length,Sepal_Width,Petal_Length,Weather_Condition,Target_Output,Is_Cloudy,Is_Rainy,Is_Sunny
0,6.1,2.8,4.7,Cloudy,0,1,0,0
1,5.7,3.8,1.7,Cloudy,0,1,0,0
2,7.7,2.6,6.9,Rainy,1,0,1,0
3,6.0,2.9,4.5,Rainy,0,0,1,0
4,6.8,2.8,4.8,Cloudy,0,1,0,0
...,...,...,...,...,...,...,...,...
95,5.5,2.5,4.0,Sunny,0,0,0,1
96,4.4,2.9,1.4,Rainy,0,0,1,0
97,4.3,3.0,1.1,Rainy,0,0,1,0
98,6.0,2.2,5.0,Cloudy,1,1,0,0
99,7.2,3.2,6.0,Sunny,1,0,0,1

In [97]:
del df2['Weather_Condition']

In [98]:
df2

,Sepal_Length,Sepal_Width,Petal_Length,Target_Output,Is_Cloudy,Is_Rainy,Is_Sunny
0,6.1,2.8,4.7,0,1,0,0
1,5.7,3.8,1.7,0,1,0,0
2,7.7,2.6,6.9,1,0,1,0
3,6.0,2.9,4.5,0,0,1,0
4,6.8,2.8,4.8,0,1,0,0
...,...,...,...,...,...,...,...
95,5.5,2.5,4.0,0,0,0,1
96,4.4,2.9,1.4,0,0,1,0
97,4.3,3.0,1.1,0,0,1,0
98,6.0,2.2,5.0,1,1,0,0
99,7.2,3.2,6.0,1,0,0,1

In [99]:
y2 = df2['Target_Output']

In [100]:
del(df2['Target_Output'])

In [101]:
X2 = df2

In [102]:
model = LinearRegression()
model.fit(X2, y2)

LinearRegression()

In [103]:
print('Intercept:', model.intercept_)
print('Coefficient:', model.coef_)

Intercept: -0.8915528991007522
Coefficient: [-0.05946381  0.22133202  0.23601317 -0.04420488  0.08041537 -0.03621049]

In [ ]:
df = pd.DataFrame({
    "Student": ["Ram", "Sita", "Hari", "Gita", "Shyam"],
    "Grade": ["B", "A", "C", "A+", "B+"]
})

In [ ]:
grade_mapping = {
    "C": 1,
    "B": 2,
    "B+": 3,
    "A": 4,
    "A+": 5
}

In [2]:
df["Grade"] = df["Grade"].map(grade_mapping)
df

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(
    categories=[["C", "B", "B+", "A", "A+"]]
)

df[["Grade"]] = encoder.fit_transform(df[["Grade"]])